### ISSUE TITLE
请求镜像 CTAN

### ISSUE THREAD

**Issue by septsea** [hust-open-atom-club/mirrorrequest#11]
### Prerequisites/先决条件

- [X] 我已确认这个镜像源从未在 [其他 issues](https://github.com/hust-open-atom-club/mirrorrequest/issues) 中讨论过。
I am sure that this repo has NEVER been discussed in [other issues](https://github.com/hust-open-atom-club/mirrorrequest/issues).

- [X] 我已确认这个镜像源没有我选择的镜像站上线。
I am sure that this repo has NOT currently be provided by the sites I select.

### 镜像简介及名称/Description and name of the Mirror

The Comprehensive TeX Archive Network (CTAN) is the central place for all kinds of material around [TeX](https://ctan.org/tex).

综合 TeX 档案网络 (CTAN) 是有关 [TeX](https://ctan.org/tex) 的各种材料的中心位置.

### 镜像源地址/Upstream URL

[https://ctan.org/](https://ctan.org/)

### 备注/note

We are convinced that mirroring CTAN helps TeX users in or near Huazhong University of Science and Technology access materials about TeX more easily and more rapidly.

我们认为, 镜像 CTAN 可以帮助华中科技大学及其附近的 TeX 用户更轻松地, 更快速地访问有关 TeX 的资料.

**Comment by Souls-R** [comment]
镜像已存在
https://mirrors.hust.edu.cn/docs/CTAN
