### ISSUE TITLE
修改镜像 CTAN

### ISSUE THREAD

**Issue by huangyxi** [hust-open-atom-club/mirrorrequest#14]
### Prerequisites/先决条件

- [X] 我确认这个镜像源已存在[HUST镜像站](https://mirrors.hust.edu.cn)。
I am sure that this repo exists in [HUST mirror station](https://mirrors.hust.edu.cn).

- [X] 我有充分的理由修改这个镜像源。
I have good reason to modify to this mirror source.

### 镜像简介及名称/Description and name of the Mirror

The Comprehensive TeX Archive Network (CTAN)，综合 TeX 档案网络是有关 [TeX](https://ctan.org/tex) 各种材料的中心位置。

### 修改理由/Reason for modifiability

1. 根据 CTAN 官方镜像注册 https://ctan.org/mirrors/register/ 说明，希望修改当前服务器 CTAN 上游镜像源至 `ctan.org` 源，作为添加到官方源列表 https://ctan.org/mirrors/ 的前置条件，以此便于均衡 CTAN 访问负载，发挥镜像网站作用。
2. 在网络可访问的前提下，使用官方提供的源作为上游同步源可以减少中间环节，降低 TeX 宏包更新的传播时间，并提高稳定性。

### 需要修改的内容/Content to be modified

将上游源从 `rsync://mirrors.tuna.tsinghua.edu.cn/CTAN/` 切换至 `rsync://rsync.dante.ctan.org/CTAN`

### 备注/note

https://github.com/hust-open-atom-club/hust-mirrors/issues/13

**Comment by mudongliang** [comment]
根据 CTAN 官方镜像注册 https://ctan.org/mirrors/register/ 说明，希望修改当前服务器 CTAN 上游镜像源至 [ctan.org](http://ctan.org/) 源，作为添加到官方源列表 https://ctan.org/mirrors/ 的前置条件，以此便于均衡 CTAN 访问负载，发挥镜像网站作用。

**Comment by mudongliang** [comment]
我们这两天会尽快注册，跟对方沟通

**Comment by huangyxi** [comment]
> 我们这两天会尽快注册，跟对方沟通

感谢支持

**Comment by mudongliang** [comment]
已经register，需要等待对方消息

**Comment by mudongliang** [comment]
<img width="381" alt="截屏2024-08-19 11 10 58" src="https://github.com/user-attachments/assets/a6f7ae57-1f45-414c-b919-f71f37956be9">


https://ctan.org/mirrors/

**Comment by mudongliang** [comment]
这个软件源我们已经切换到上游了
