### ISSUE TITLE
修改镜像 CRAN

### ISSUE THREAD

**Issue by huangyxi** [hust-open-atom-club/mirrorrequest#15]
### Prerequisites/先决条件

- [X] 我确认这个镜像源已存在[HUST镜像站](https://mirrors.hust.edu.cn)。
I am sure that this repo exists in [HUST mirror station](https://mirrors.hust.edu.cn).

- [X] 我有充分的理由修改这个镜像源。
I have good reason to modify to this mirror source.

### 镜像简介及名称/Description and name of the Mirror

The Comprehensive R Archive Network (CRAN), 综合 R 档案网络是有关 [R语言](https://www.r-project.org/) 各种材料的中心位置。

### 修改理由/Reason for modifiability

1. 根据 CTAN 官方镜像注册 https://cran.r-project.org/mirror-howto.html 说明，希望修改当前服务器 CRAN 上游镜像源至 r-project.org 源，作为添加到官方源列表 https://cran.r-project.org/mirrors.html 的前置条件，以此便于均衡 CRAN 访问负载，发挥镜像网站作用。
2. 在网络可访问的前提下，使用官方提供的源作为上游同步源可以减少中间环节，降低 R 语言包更新的传播时间，并提高稳定性。

### 需要修改的内容/Content to be modified

1. 
> For security reasons we furthermore recommend mirroring over an SSH tunnel.
> For rsync over ssh please send your public SSH key to [cran-sysadmin@r-project.org](mailto:cran-sysadmin@r-project.org) in advance (only requests from organizations are considered) ...

以镜像服务器管理者身份将服务器 ssh 公钥发送至 `cran-sysadmin@r-project.org`。

2. 使用基于 ssh 的 rsync 同步，修改同步指令类似于：
```bash
rsync -e "ssh" -rptlzv --delete cran-rsync@cran.r-project.org::CRAN /dir/on/local/disc
```

### 备注/note

https://github.com/hust-open-atom-club/hust-mirrors/issues/13

**Comment by mudongliang** [comment]
我们已经将服务器公开 SSH 公钥发给对方了
