### ISSUE TITLE
请求镜像 MSYS 

### ISSUE THREAD

**Issue by taozuhong** [hust-open-atom-club/mirrorrequest#16]
### Prerequisites/先决条件

- [X] 我已确认这个镜像源从未在 [其他 issues](https://github.com/hust-open-atom-club/mirrorrequest/issues) 中讨论过。
I am sure that this repo has NEVER been discussed in [other issues](https://github.com/hust-open-atom-club/mirrorrequest/issues).

- [X] 我已确认这个镜像源没有我选择的镜像站上线。
I am sure that this repo has NOT currently be provided by the sites I select.

### 镜像简介及名称/Description and name of the Mirror

MSYS2 软件仓库

### 镜像源地址/Upstream URL

https://mirrors.tuna.tsinghua.edu.cn/msys2/mingw

### 备注/note

这个仓库用于构建一些跨平台的应用，很多软件用到它

**Comment by huangyxi** [comment]
建议如果镜像的话使用官方源 Primary Server (rsync://repo.msys2.org/builds/)，参见
https://www.msys2.org/dev/mirrors/

**Comment by mudongliang** [comment]
一般我们先使用国内源进行基础同步，然后切换上游源
