### ISSUE TITLE
请求镜像 Gentoo

### ISSUE THREAD

**Issue by jiaxing-liu** [hust-open-atom-club/mirrorrequest#19]
### Prerequisites/先决条件

- [X] 我已确认这个镜像源从未在 [其他 issues](https://github.com/hust-open-atom-club/mirrorrequest/issues) 中讨论过。
I am sure that this repo has NEVER been discussed in [other issues](https://github.com/hust-open-atom-club/mirrorrequest/issues).

- [X] 我已确认这个镜像源没有我选择的镜像站上线。
I am sure that this repo has NOT currently be provided by the sites I select.

### 镜像简介及名称/Description and name of the Mirror

镜像名称 Gentoo
镜像源 
rsync://masterdistfiles.gentoo.org/gentoo

### 镜像源地址/Upstream URL

rsync://masterdistfiles.gentoo.org/gentoo

**Comment by mudongliang** [comment]
It seems the sync from tuna is done. However, the size is different, we need to figure out the reason. So let's keep this issue as syncing.
