### ISSUE TITLE
请添加Rocky Linux镜像和配置方法，务必测试后上架

### ISSUE THREAD

**Issue by linzhengwu** [hust-open-atom-club/mirrorrequest#20]
### Prerequisites/先决条件

- [X] 我已确认这个镜像源从未在 [其他 issues](https://github.com/hust-open-atom-club/mirrorrequest/issues) 中讨论过。
I am sure that this repo has NEVER been discussed in [other issues](https://github.com/hust-open-atom-club/mirrorrequest/issues).

- [X] 我已确认这个镜像源没有我选择的镜像站上线。
I am sure that this repo has NOT currently be provided by the sites I select.

### 镜像简介及名称/Description and name of the Mirror

Rocky Linux镜像

### 镜像源地址/Upstream URL

https://mirrors.ustc.edu.cn/rocky/          #这是中科大的镜像源可以从这里同步

### 备注/note

https://mirrors.ustc.edu.cn/rocky/          #这是中科大的镜像源可以从这里同步

**Comment by mudongliang** [comment]
在移除该issue之前，我们需要对该镜像进行进行测试

**Comment by tttturtle-russ** [comment]
## Result(LGTM)
- Rockylinux8.9
![image](https://github.com/user-attachments/assets/f55b1c83-1235-4cde-8851-ea3b1aa97fc9)

- Rockylinux9.3
![image](https://github.com/user-attachments/assets/7e2abdbe-044c-477e-a3ac-d21cd6bd3369)
