### ISSUE TITLE
请求镜像：Vagrant boxes

### ISSUE THREAD

**Issue by tttturtle-russ** [hust-open-atom-club/mirrorrequest#3]
### Prerequisites/先决条件

- [X] 我已确认这个镜像源从未在 [其他 issues](https://github.com/hust-open-atom-club/mirrorrequest/issues) 中讨论过。
I am sure that this repo has NEVER been discussed in [other issues](https://github.com/hust-open-atom-club/mirrorrequest/issues).

- [X] 我已确认这个镜像源没有我选择的镜像站上线。
I am sure that this repo has NOT currently be provided by the sites I select.

### 镜像简介及名称/Description and name of the Mirror

Vagrant是一款用于构建及配置虚拟开发环境的软件，采用Ruby编写，主要以命令行方式运行。可以实现快速搭建虚拟开发环境。

Vagrant boxes是Vagrant环境所使用的包。

相关链接：https://app.vagrantup.com/boxes/search

### 镜像源地址/Upstream URL

N/A

**Comment by mudongliang** [comment]
这个需求是我提的，但是目前感觉没有什么需求了，所以暂时关闭
