### ISSUE TITLE
请求镜像：ubuntu-ports

### ISSUE THREAD

**Issue by jxlpzqc** [hust-open-atom-club/mirrorrequest#5]
### Prerequisites/先决条件

- [X] 我已确认这个镜像源从未在 [其他 issues](https://github.com/hust-open-atom-club/mirrorrequest/issues) 中讨论过。
I am sure that this repo has NEVER been discussed in [other issues](https://github.com/hust-open-atom-club/mirrorrequest/issues).

- [X] 我已确认这个镜像源没有我选择的镜像站上线。
I am sure that this repo has NOT currently be provided by the sites I select.

### 镜像简介及名称/Description and name of the Mirror

ubuntu-ports

### 镜像源地址/Upstream URL

rsync://ports.ubuntu.com/ubuntu-ports/

**Comment by Lxy12138** [comment]
支持！添加ARM架构的ubuntu镜像

**Comment by mudongliang** [comment]
本镜像站将先通过tuna进行更新，然后切换上游镜像源
