### ISSUE TITLE
请求镜像 - ArchLinuxCN

### ISSUE THREAD

**Issue by xoozjay** [hust-open-atom-club/mirrorrequest#6]
### Prerequisites/先决条件

- [X] 我已确认这个镜像源从未在 [其他 issues](https://github.com/hust-open-atom-club/mirrorrequest/issues) 中讨论过。
I am sure that this repo has NEVER been discussed in [other issues](https://github.com/hust-open-atom-club/mirrorrequest/issues).

- [X] 我已确认这个镜像源没有我选择的镜像站上线。
I am sure that this repo has NOT currently be provided by the sites I select.

### 镜像简介及名称/Description and name of the Mirror

> Arch Linux 中文社区仓库是由 Arch Linux 中文社区驱动的非官方软件仓库，包含许多官方仓库未提供的额外的软件包，以及已有软件的 git 版本等变种。一部分软件包的打包脚本来源于 AUR，但也有许多包与 AUR 不一样。

事实上，archlinuxcn 是许多 cn archer 的必选仓库之一， [archlinuxcn] 仓库提供许多额外的、已经打包好的软件。相比于 AUR，您不必在本地从世界各个地方下载软件源码然后花费时间编译。您直接安装已经编译好的软件包。

### 镜像源地址/Upstream URL

https://repo.archlinuxcn.org/

### 备注/note

> If you interested in making a mirror of our repository, please open an issue or pull request (or contact us at [repo@archlinuxcn.org](mailto:repo@archlinuxcn.org) and hope the mail reaches).

https://github.com/archlinuxcn/mirrorlist-repo

**Comment by tttturtle-russ** [comment]
已添加，后续会加入官方镜像列表 https://github.com/hust-open-atom-club/hust-mirrors/issues/13#issuecomment-2084396461

**Comment by jxlpzqc** [comment]
已经同步 @xoozjay

**Comment by tttturtle-russ** [comment]
镜像站工具`hustmirror-cli`已经上传到ArchLinuxCN仓库 https://github.com/archlinuxcn/repo/commit/486a4c4dbef27de11953ecb3af28dfc92d2942a8
